"use client"

import { cn } from "@/lib/utils"
import { useI18n } from "@/lib/i18n"
import { Shield, Globe, FileText, Trash2, Scale, Clock, Database, Eye, BrainCircuit, Cog, AlertTriangle, Lock, KeyRound, Server, Mail, AlertOctagon, HelpCircle } from "lucide-react"

const sections = {
  en: [
    {
      icon: BrainCircuit,
      title: "1. AI-Powered Services",
      body: `Exploro OS provides access to artificial intelligence ("AI") technologies, including Large Language Models ("LLMs"), machine learning systems, recommendation engines, automation tools, and third-party AI services. By using Exploro OS, you acknowledge and agree that certain outputs, recommendations, analyses, and responses are generated by automated systems and may not always be accurate, complete, current, or suitable for your specific circumstances.`,
    },
    {
      icon: Database,
      title: "2. User Data Processing",
      body: `To provide AI-powered functionality, Exploro OS may process information submitted by users, including: text prompts, uploaded files and documents, images, audio, and video content, workflow configurations, business information, and user preferences and settings. Such information may be transmitted to, processed by, or stored through Exploro OS infrastructure and authorized third-party AI service providers. Exploro OS processes data solely for purposes including: delivering requested AI services, improving platform functionality, security monitoring and fraud prevention, service analytics, and product development and optimization.`,
    },
    {
      icon: Globe,
      title: "3. Third-Party AI Providers",
      body: `Exploro OS may integrate with third-party AI providers, including but not limited to providers of language models, image generation systems, speech recognition systems, automation services, and data analytics tools. When user inputs are submitted through such integrations, data may be transferred to those providers. Such providers may process data according to their own privacy policies and terms. Exploro OS is not responsible for the independent practices of third-party providers. Users are encouraged to review applicable third-party privacy notices before using connected services.`,
    },
    {
      icon: Cog,
      title: "4. AI Model Training and Improvement",
      body: `Unless otherwise specified in a separate enterprise agreement, Exploro OS may use anonymized, aggregated, and de-identified usage data to: improve platform performance, enhance recommendation systems, develop new features, and analyze service effectiveness. Exploro OS will not intentionally use personally identifiable information for AI training without an appropriate legal basis or explicit user consent where required by applicable law. Users may request exclusion from certain improvement programs where legally required.`,
    },
    {
      icon: Shield,
      title: "5. User Responsibilities",
      body: `Users agree not to submit: unlawfully obtained information, confidential information without authorization, intellectual property owned by third parties without permission, personal data of others without legal authority, or content that violates applicable laws or regulations. Users remain solely responsible for all information submitted to the platform.`,
    },
    {
      icon: AlertTriangle,
      title: "6. AI Output Disclaimer",
      body: `AI-generated content may contain inaccuracies, omissions, biases, outdated information, or unintended results. Exploro OS does not warrant that AI-generated outputs are: factually accurate, legally compliant, financially sound, medically appropriate, or professionally suitable for any specific purpose. Users should independently verify important information before making decisions based on AI-generated outputs.`,
    },
    {
      icon: Scale,
      title: "7. No Professional Advice",
      body: `Unless expressly stated otherwise, AI-generated content does not constitute: legal advice, medical advice, financial advice, investment advice, tax advice, or regulatory advice. Users should consult qualified professionals before relying upon AI-generated recommendations in regulated or high-risk situations.`,
    },
    {
      icon: Lock,
      title: "8. Data Security",
      body: `Exploro OS implements commercially reasonable administrative, technical, and organizational measures designed to protect user data from unauthorized access, disclosure, alteration, or destruction. No method of transmission or electronic storage can be guaranteed as completely secure, and users acknowledge such inherent risks.`,
    },
    {
      icon: Globe,
      title: "9. International Data Transfers",
      body: `User information may be processed and stored in jurisdictions outside the user's country of residence. Where required by law, Exploro OS will implement appropriate safeguards for international data transfers, including contractual protections and recognized data protection mechanisms.`,
    },
    {
      icon: FileText,
      title: "10. Intellectual Property of AI Outputs",
      body: `Subject to applicable law and third-party provider restrictions: Users retain ownership of content they submit. Users may use AI-generated outputs produced through their lawful use of the platform. Exploro OS retains ownership of its platform, software, algorithms, workflows, recommendation systems, and proprietary technologies. Users acknowledge that AI-generated content may not be unique and similar outputs may be generated for other users.`,
    },
    {
      icon: Cog,
      title: "11. Automated Decision-Making",
      body: `Certain platform features may utilize automated processing to generate recommendations, rankings, workflow suggestions, or predictive analyses. Such outputs are intended as decision-support tools and should not be considered binding decisions made by Exploro OS.`,
    },
    {
      icon: Scale,
      title: "12. Regulatory Compliance",
      body: `Exploro OS endeavors to comply with applicable data protection laws, including where applicable: General Data Protection Regulation (GDPR), California Consumer Privacy Act (CCPA), UAE Personal Data Protection Law (PDPL), Singapore Personal Data Protection Act (PDPA), and other applicable privacy and consumer protection regulations. Users may exercise applicable privacy rights as provided by law.`,
    },
    {
      icon: AlertOctagon,
      title: "13. Limitation of Liability",
      body: `To the maximum extent permitted by law, Exploro OS shall not be liable for any loss, damage, claim, or liability arising from: reliance upon AI-generated outputs, errors or omissions in AI responses, third-party AI provider failures, automated recommendations, or business, financial, legal, medical, or operational decisions made by users. Users assume all risks associated with the use of AI-generated content.`,
    },
    {
      icon: Clock,
      title: "14. Changes to AI Services",
      body: `Exploro OS reserves the right to modify, replace, suspend, or discontinue any AI model, provider, functionality, or feature at any time without prior notice. Continued use of the platform constitutes acceptance of such changes.`,
    },
    {
      icon: HelpCircle,
      title: "15. Contact Regarding Privacy and AI Usage",
      body: `Questions regarding AI processing, privacy rights, data requests, or compliance matters may be submitted through the official Exploro OS privacy contact channels.`,
    },
    {
      icon: KeyRound,
      title: "16. Google Data Access",
      body: `Exploro allows users to connect Google services such as Gmail and Google Calendar to provide AI-powered business assistance. When users authorize Google services, Exploro may access email messages, calendar events, and related account information required for these features.`,
    },
    {
      icon: Eye,
      title: "17. How Google Data Is Used",
      body: `Google data is used only to provide requested functionality such as displaying emails, organizing conversations, creating summaries, and managing calendar information inside the user's Exploro workspace.`,
    },
    {
      icon: Server,
      title: "18. Storage",
      body: `OAuth tokens and connected account information are securely stored to maintain user connections. User Google data is isolated per workspace and is not sold or used to train public AI models.`,
    },
    {
      icon: Trash2,
      title: "19. Deletion",
      body: `Users can disconnect Google services at any time. Upon account deletion, associated stored data is removed according to our retention policy.`,
    },
  ],
  es: [
    {
      icon: BrainCircuit,
      title: "1. Servicios Impulsados por IA",
      body: `Exploro OS proporciona acceso a tecnologías de inteligencia artificial ("IA"), incluyendo Modelos de Lenguaje Grande ("LLMs"), sistemas de aprendizaje automático, motores de recomendación, herramientas de automatización y servicios de IA de terceros. Al usar Exploro OS, usted reconoce y acepta que ciertos resultados, recomendaciones, análisis y respuestas son generados por sistemas automatizados y pueden no ser siempre precisos, completos, actuales o adecuados para sus circunstancias específicas.`,
    },
    {
      icon: Database,
      title: "2. Procesamiento de Datos del Usuario",
      body: `Para proporcionar funcionalidad impulsada por IA, Exploro OS puede procesar información enviada por los usuarios, incluyendo: indicaciones de texto, archivos y documentos cargados, imágenes, audio y contenido de video, configuraciones de flujos de trabajo, información comercial, y preferencias y ajustes del usuario.`,
    },
    {
      icon: Globe,
      title: "3. Proveedores de IA de Terceros",
      body: `Exploro OS puede integrarse con proveedores de IA de terceros, incluyendo pero no limitado a: modelos de lenguaje, sistemas de generación de imágenes, sistemas de reconocimiento de voz, servicios de automatización y herramientas de análisis de datos.`,
    },
    {
      icon: Cog,
      title: "4. Entrenamiento y Mejora de Modelos de IA",
      body: `A menos que se especifique lo contrario en un acuerdo empresarial separado, Exploro OS puede usar datos de uso anonimizados, agregados y desidentificados para: mejorar el rendimiento de la plataforma, mejorar los sistemas de recomendación, desarrollar nuevas funciones y analizar la efectividad del servicio.`,
    },
    {
      icon: Shield,
      title: "5. Responsabilidades del Usuario",
      body: `Los usuarios aceptan no enviar: información obtenida ilegalmente, información confidencial sin autorización, propiedad intelectual de terceros sin permiso, datos personales de otros sin autoridad legal, o contenido que viole leyes o regulaciones aplicables.`,
    },
    {
      icon: AlertTriangle,
      title: "6. Descargo de Responsabilidad de Resultados de IA",
      body: `El contenido generado por IA puede contener inexactitudes, omisiones, sesgos, información desactualizada o resultados no deseados. Exploro OS no garantiza que los resultados generados por IA sean: factualmente precisos, legalmente conformes, financieramente sólidos, médicamente apropiados o profesionalmente adecuados para cualquier propósito específico.`,
    },
    {
      icon: Scale,
      title: "7. Sin Asesoramiento Profesional",
      body: `A menos que se indique expresamente lo contrario, el contenido generado por IA no constituye: asesoramiento legal, médico, financiero, de inversión, fiscal o regulatorio. Los usuarios deben consultar profesionales calificados antes de confiar en recomendaciones generadas por IA en situaciones reguladas o de alto riesgo.`,
    },
    {
      icon: Lock,
      title: "8. Seguridad de Datos",
      body: `Exploro OS implementa medidas administrativas, técnicas y organizativas comercialmente razonables diseñadas para proteger los datos del usuario contra acceso, divulgación, alteración o destrucción no autorizados.`,
    },
    {
      icon: Globe,
      title: "9. Transferencias Internacionales de Datos",
      body: `La información del usuario puede ser procesada y almacenada en jurisdicciones fuera del país de residencia del usuario. Cuando lo exija la ley, Exploro OS implementará salvaguardas apropiadas para las transferencias internacionales de datos.`,
    },
    {
      icon: FileText,
      title: "10. Propiedad Intelectual de los Resultados de IA",
      body: `Sujeto a la ley aplicable y las restricciones de proveedores de terceros: Los usuarios retienen la propiedad del contenido que envían. Los usuarios pueden usar los resultados generados por IA producidos a través de su uso legítimo de la plataforma. Exploro OS retiene la propiedad de su plataforma, software, algoritmos, flujos de trabajo y tecnologías propietarias.`,
    },
    {
      icon: Cog,
      title: "11. Toma de Decisiones Automatizada",
      body: `Ciertas funciones de la plataforma pueden utilizar procesamiento automatizado para generar recomendaciones, clasificaciones, sugerencias de flujos de trabajo o análisis predictivos. Tales resultados están destinados como herramientas de apoyo a la decisión y no deben considerarse decisiones vinculantes de Exploro OS.`,
    },
    {
      icon: Scale,
      title: "12. Cumplimiento Normativo",
      body: `Exploro OS se esfuerza por cumplir con las leyes de protección de datos aplicables, incluyendo cuando corresponda: Reglamento General de Protección de Datos (GDPR), Ley de Privacidad del Consumidor de California (CCPA), Ley de Protección de Datos Personales de los EAU (PDPL), Ley de Protección de Datos Personales de Singapur (PDPA) y otras regulaciones aplicables.`,
    },
    {
      icon: AlertOctagon,
      title: "13. Limitación de Responsabilidad",
      body: `En la medida máxima permitida por la ley, Exploro OS no será responsable por ninguna pérdida, daño, reclamo o responsabilidad derivados de: confianza en resultados generados por IA, errores u omisiones en respuestas de IA, fallas de proveedores de IA de terceros, recomendaciones automatizadas o decisiones comerciales, financieras, legales, médicas u operativas tomadas por los usuarios.`,
    },
    {
      icon: Clock,
      title: "14. Cambios en los Servicios de IA",
      body: `Exploro OS se reserva el derecho de modificar, reemplazar, suspender o discontinuar cualquier modelo de IA, proveedor, funcionalidad o característica en cualquier momento sin previo aviso. El uso continuo de la plataforma constituye la aceptación de dichos cambios.`,
    },
    {
      icon: HelpCircle,
      title: "15. Contacto sobre Privacidad y Uso de IA",
      body: `Las preguntas sobre procesamiento de IA, derechos de privacidad, solicitudes de datos o asuntos de cumplimiento pueden enviarse a través de los canales oficiales de contacto de privacidad de Exploro OS.`,
    },
    {
      icon: KeyRound,
      title: "16. Acceso a Datos de Google",
      body: `Exploro permite a los usuarios conectar servicios de Google como Gmail y Google Calendar para proporcionar asistencia comercial impulsada por IA. Cuando los usuarios autorizan los servicios de Google, Exploro puede acceder a mensajes de correo electrónico, eventos de calendario e información relacionada de la cuenta requerida para estas funciones.`,
    },
    {
      icon: Eye,
      title: "17. Cómo se Usan los Datos de Google",
      body: `Los datos de Google se utilizan únicamente para proporcionar la funcionalidad solicitada, como mostrar correos electrónicos, organizar conversaciones, crear resúmenes y gestionar información de calendario dentro del espacio de trabajo Exploro del usuario.`,
    },
    {
      icon: Server,
      title: "18. Almacenamiento",
      body: `Los tokens OAuth y la información de cuentas conectadas se almacenan de forma segura para mantener las conexiones de los usuarios. Los datos de Google de los usuarios están aislados por espacio de trabajo y no se venden ni se utilizan para entrenar modelos de IA públicos.`,
    },
    {
      icon: Trash2,
      title: "19. Eliminación",
      body: `Los usuarios pueden desconectar los servicios de Google en cualquier momento. Al eliminar la cuenta, los datos almacenados asociados se eliminan de acuerdo con nuestra política de retención.`,
    },
  ],
}

const jurisdictions = {
  en: [
    { law: "LFPDPPP", jurisdiction: "Mexico", applicability: "All clients operating in Mexico" },
    { law: "GDPR (Regulation EU 2016/679)", jurisdiction: "European Union", applicability: "All clients who are EU residents or process EU citizen data" },
    { law: "CCPA/CPRA (Cal. Civ. Code § 1798.100 et seq.)", jurisdiction: "California, USA", applicability: "Clients with California residents in their database" },
    { law: "PIPEDA", jurisdiction: "Canada", applicability: "Clients operating in Canada" },
    { law: "LGPD (Lei Geral de Proteção de Dados)", jurisdiction: "Brazil", applicability: "Clients operating in Brazil" },
  ],
  es: [
    { law: "LFPDPPP", jurisdiction: "México", applicability: "Todos los clientes que operan en México" },
    { law: "GDPR (Reglamento UE 2016/679)", jurisdiction: "Unión Europea", applicability: "Clientes residentes en la UE o que procesan datos de ciudadanos UE" },
    { law: "CCPA/CPRA (Cal. Civ. Code § 1798.100 et seq.)", jurisdiction: "California, EE.UU.", applicability: "Clientes con residentes de California en su base de datos" },
    { law: "PIPEDA", jurisdiction: "Canadá", applicability: "Clientes que operan en Canadá" },
    { law: "LGPD (Lei Geral de Proteção de Dados)", jurisdiction: "Brasil", applicability: "Clientes que operan en Brasil" },
  ],
}

const notices = {
  en: {
    popupTitle: "PRIVATE DATA LEGAL NOTICE",
    intro: "Your customer data is protected under the following applicable laws:",
    rightsTitle: "Your rights (GDPR Art. 17 & 20 / LFPDPPP Art. 22-26):",
    rights: [
      "Full ownership of your data",
      "Export your data at any time",
      "Request permanent deletion within 30 days of cancellation",
    ],
    obligationsTitle: "Platform obligations (LFPDPPP Title II / GDPR Art. 28):",
    obligations: [
      "We act exclusively as Data Processor",
      "You remain the Data Controller",
      "Your data never trains public AI models",
    ],
    transparencyTitle: "Source transparency commitment:",
    transparency: [
      "Every response cites internal vs external sources",
      "External web research includes citations",
      "Minimum hallucinated data, you verify before use",
    ],
    liabilityTitle: "Limitation of liability (Section 4 of Service Agreement):",
    liability: [
      "We are not liable for decisions you make based on AI-generated outputs",
      "We are not liable for third-party platform interruptions",
    ],
    acceptance: "By continuing to use this CRM dashboard, you confirm acceptance of these legal terms.",
    acceptanceBanner: "ACCEPTANCE AND DIGITAL AUTHORIZATION — By signing up, contracting services, and/or making payment, the Client declares that: (1) they have read and fully understand this Private Data Disclaimer, (2) they authorize the use of AI technologies for data processing with business purposes, and (3) their electronic registration constitutes a binding signature under applicable e-commerce laws.",
  },
  es: {
    popupTitle: "AVISO LEGAL DE DATOS PRIVADOS",
    intro: "Tus datos están protegidos bajo las siguientes leyes aplicables:",
    rightsTitle: "Tus derechos (GDPR Art. 17 & 20 / LFPDPPP Art. 22-26):",
    rights: [
      "Propiedad total de sus datos",
      "Exportación y eliminación en cualquier momento",
      "Tus datos nunca entrenan modelos públicos de IA",
    ],
    obligationsTitle: "Responsabilidad de La Plataforma:",
    obligations: [
      "Actuamos solo como procesadora de datos",
      "Cada respuesta cita fuentes internas y externas",
      "No somos responsables por resultados generados por tu agente de IA",
    ],
    transparencyTitle: "Transparencia de fuentes:",
    transparency: [
      "Cada resultado cita fuentes internas vs externas",
      "Investigación web externa incluye citas",
      "Datos alucinados mínimos, verifíquelos antes de usarlos",
    ],
    liabilityTitle: "Limitación de responsabilidad (Sección 4 del Acuerdo de Servicio):",
    liability: [
      "No somos responsables por decisiones basadas en resultados generados por IA",
      "No somos responsables por interrupciones de plataformas de terceros",
    ],
    acceptance: "Al continuar usando el CRM, estás confirmando y aceptas estos términos.",
    acceptanceBanner: "ACEPTACIÓN Y AUTORIZACIÓN DIGITAL — Al registrarse, contratar servicios y/o realizar el pago, el Cliente declara que: (1) ha leído y comprende en su totalidad este Aviso de Datos Privados, (2) autoriza el uso de tecnologías de IA para el procesamiento de datos con fines comerciales, y (3) su registro electrónico constituye una firma vinculante conforme a las leyes aplicables de comercio electrónico.",
  },
}

export default function PrivacyPage() {
  const { lang } = useI18n()
  const t = sections[lang as "en" | "es"]
  const j = jurisdictions[lang as "en" | "es"]
  const n = notices[lang as "en" | "es"]

  return (
    <>
        {/* Hero */}
        <section className="border-b border-white/5 bg-[#1a1f2e] py-16 md:py-24">
          <div className="mx-auto max-w-4xl px-6">
            <div className="mb-6 flex items-center gap-3">
              <Shield className="h-8 w-8 text-emerald-400" />
              <span className="text-xs font-semibold uppercase tracking-wider text-emerald-400">{lang === "en" ? "Legal" : "Legal"}</span>
            </div>
            <h1 className="text-3xl font-bold tracking-tight text-white md:text-5xl">
              {lang === "en" ? "International Data Protection Disclaimer" : "Aviso de Datos Privados: Protección de Clientes y Leads"}
            </h1>
            <p className="mt-4 max-w-2xl text-lg text-muted-foreground">
              {lang === "en"
                ? "Exploro OS (\"The Platform\") provides private GPT services, data analysis, reporting, and AI-assisted communication tools. This disclaimer governs how your customer data, leads, and business information are processed, stored, and protected."
                : 'Exploro OS ("La Plataforma") proporciona servicios de GPT privado, análisis de datos, reportes y herramientas de comunicación asistidas por IA. Este aviso rige la forma en que sus datos de clientes, leads e información comercial son procesados, almacenados y protegidos.'}
            </p>
          </div>
        </section>

        {/* Sections */}
        <section className="mx-auto max-w-4xl px-6 py-12 md:py-16">
          <div className="space-y-8">
            {t.map((section, i) => (
              <div key={i} className="rounded-2xl border border-white/5 bg-[#1e2330] p-6 md:p-8">
                <div className="mb-4 flex items-center gap-3">
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-emerald-600/10">
                    <section.icon className="h-5 w-5 text-emerald-400" />
                  </div>
                  <h2 className="text-lg font-semibold text-white">{section.title}</h2>
                </div>
                <p className="text-sm leading-relaxed text-muted-foreground">{section.body}</p>
                {(section as any).source && <p className="mt-3 text-xs italic text-muted-foreground/60">{(section as any).source}</p>}
              </div>
            ))}
          </div>
        </section>

        {/* Jurisdiction Table */}
        <section className="border-y border-white/5 bg-[#1a1f2e] py-12 md:py-16">
          <div className="mx-auto max-w-4xl px-6">
            <h2 className="mb-8 text-xl font-semibold text-white">
              {lang === "en" ? "Applicable Privacy Laws by Jurisdiction" : "Leyes de Privacidad Aplicables por Jurisdicción"}
            </h2>
            <div className="overflow-x-auto rounded-2xl border border-white/10">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-white/10 bg-[#252b3a]">
                    <th className="px-4 py-3 text-left font-semibold text-white">{lang === "en" ? "Law" : "Ley"}</th>
                    <th className="px-4 py-3 text-left font-semibold text-white">{lang === "en" ? "Jurisdiction" : "Jurisdicción"}</th>
                    <th className="px-4 py-3 text-left font-semibold text-white">{lang === "en" ? "Applicability" : "Aplicabilidad"}</th>
                  </tr>
                </thead>
                <tbody>
                  {j.map((row, i) => (
                    <tr key={i} className={cn("border-b border-white/5", i % 2 === 0 ? "bg-[#1e2330]" : "bg-[#1a1f2e]")}>
                      <td className="px-4 py-3 font-medium text-emerald-400">{row.law}</td>
                      <td className="px-4 py-3 text-white">{row.jurisdiction}</td>
                      <td className="px-4 py-3 text-muted-foreground">{row.applicability}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </section>

        {/* CRM Pop-up Notice */}
        <section className="mx-auto max-w-4xl px-6 py-12 md:py-16">
          <h2 className="mb-8 text-xl font-semibold text-white">
            {lang === "en" ? "CRM Dashboard Notice" : "Aviso del Panel de CRM"}
          </h2>
          <div className="rounded-2xl border border-white/10 bg-[#1e2330] p-6 md:p-8">
            <div className="mb-6 flex items-center gap-3">
              <Shield className="h-6 w-6 text-emerald-400" />
              <h3 className="text-lg font-semibold text-white">{n.popupTitle}</h3>
            </div>
            <p className="mb-4 text-sm text-muted-foreground">{n.intro}</p>
            <div className="mb-4 grid gap-2 sm:grid-cols-2">
              {j.map((row, i) => (
                <div key={i} className="flex items-center gap-2 text-sm">
                  <span className="h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-400" />
                  <span className="text-muted-foreground">{row.jurisdiction}: <span className="text-white">{row.law}</span></span>
                </div>
              ))}
            </div>

            <div className="space-y-4">
              <div>
                <h4 className="mb-2 text-sm font-semibold text-white">{n.rightsTitle}</h4>
                <ul className="space-y-1">
                  {n.rights.map((r, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
                      <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-emerald-400" />
                      {r}
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <h4 className="mb-2 text-sm font-semibold text-white">{n.obligationsTitle}</h4>
                <ul className="space-y-1">
                  {n.obligations.map((o, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
                      <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-emerald-400" />
                      {o}
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <h4 className="mb-2 text-sm font-semibold text-white">{n.transparencyTitle}</h4>
                <ul className="space-y-1">
                  {n.transparency.map((t, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
                      <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-emerald-400" />
                      {t}
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <h4 className="mb-2 text-sm font-semibold text-white">{n.liabilityTitle}</h4>
                <ul className="space-y-1">
                  {n.liability.map((l, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
                      <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-emerald-400" />
                      {l}
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            <div className="mt-6 rounded-xl border border-emerald-500/20 bg-emerald-600/5 p-4">
              <p className="text-sm text-emerald-400">{n.acceptance}</p>
            </div>
          </div>
        </section>

        {/* Acceptance Banner */}
        <section className="border-t border-white/5 bg-[#1a1f2e] py-8">
          <div className="mx-auto max-w-4xl px-6">
            <div className="rounded-2xl border border-white/10 bg-[#1e2330] p-6">
              <p className="text-sm leading-relaxed text-muted-foreground">{n.acceptanceBanner}</p>
            </div>
          </div>
        </section>
    </>
  )
}
